### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by andywu1998** [Meituan-Dianping/cat-go#20]
../../../../pkg/mod/github.com/!meituan-!dianping/cat-go@v2.0.0+incompatible/cat/monitor_collector.go:115:16: currentTime.Stolen undefined (type cpu.TimesStat has no field or method Stolen)

看了一下应该是因为依赖的github.com/shirou/gopsutil@v3.21.11+incompatible/cpu/cpu.go 这个库导致的。

可能是因为版本不兼容的问题？

**Comment by springshi1314** [comment]
请问这个问题解决了吗

**Comment by andywu1998** [comment]
@springshi1314 后来没有继续做这个工作了，我自己fork一个版本然后把它缺失的这个currentTime.Stolen undefined (type cpu.TimesStat has no field or method Stolen) 字段删掉，就可以编译了。当时还问了美团的同学，据说好像不维护这个了，go的得去另外一个库。
